# Generated by Django 3.1.2 on 2020-11-07 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20201014_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('friendly_name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datapack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('race_setup', models.FileField(blank=True, null=True, upload_to='datapacks/setups/')),
                ('qual_setup', models.FileField(blank=True, null=True, upload_to='datapacks/setups/')),
                ('telemetry', models.FileField(blank=True, null=True, upload_to='datapacks/telemetry/')),
                ('blap', models.FileField(blank=True, null=True, upload_to='datapacks/lapfiles/')),
                ('olap', models.FileField(blank=True, null=True, upload_to='datapacks/lapfiles/')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('track_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapacks.racetrack')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datapacks.week')),
            ],
        ),
    ]
